"""initial schema

Revision ID: d8ed23b23f21
Revises: 
Create Date: 2026-02-26 18:44:25.015359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd8ed23b23f21'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaign',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('active', 'paused', 'completed', 'archived', name='campaignstatus'), nullable=False),
    sa.Column('priority_rank', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('weekly_block_target', sa.Integer(), nullable=False),
    sa.Column('colour', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tags', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dailycheckin',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('energy_level', sa.Enum('green', 'yellow', 'red', name='energylevel'), nullable=False),
    sa.Column('available_blocks', sa.Integer(), nullable=False),
    sa.Column('focus_note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mission',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('not_started', 'in_progress', 'blocked', 'completed', name='missionstatus'), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sortie',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('mission_id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cognitive_load', sa.Enum('deep', 'medium', 'light', name='cognitiveload'), nullable=False),
    sa.Column('estimated_blocks', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'active', 'completed', 'abandoned', name='sortiestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mission_id'], ['mission.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('aar',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sortie_id', sa.Uuid(), nullable=False),
    sa.Column('energy_before', sa.Enum('green', 'yellow', 'red', name='energylevel'), nullable=False),
    sa.Column('energy_after', sa.Enum('green', 'yellow', 'red', name='energylevel'), nullable=False),
    sa.Column('outcome', sa.Enum('completed', 'partial', 'blocked', 'pivoted', name='aaroutcome'), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('actual_blocks', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sortie_id'], ['sortie.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aar')
    op.drop_table('sortie')
    op.drop_table('mission')
    op.drop_table('dailycheckin')
    op.drop_table('campaign')
    # ### end Alembic commands ###
